# You can test your setup of calling workflows here by loading this workflow:

name: Echo all available metadata

on:
  push:

jobs:
  metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Output Run Attempt
        run: echo ${{ github.run_attempt }}
