name: Environment Variables

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: CI
      run: echo ${{ vars.CI }}
    - 
      name: GITHUB_JOB
      run: echo ${{ vars.GITHUB_JOB }}
    - 
      name: GITHUB_JOB x
      run: echo ${GITHUB_JOB}
    - 
      name: printenv
      run: printenv
    - 
      name: printenv GITHUB
      run: printenv | grep ^GITHUB
