# You can test your setup of calling workflows here by loading this workflow:

name: Hello World

on:
  workflow_call:

jobs:
  hello-world:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World"
