name: Parse semver string

on:
  push:

jobs:
  test_semver_parser:
    runs-on: ubuntu-latest
    steps:
     - name: Parse semver string job
       id: semver_parser 
       uses: booxmedialtd/ws-action-parse-semver@v1
       with:
         input_string: 'refs/tags/v1.0.4'
         version_extractor_regex: '\/v(.*)$'
     - name: Use parsed semver
       run: |
            echo "v${{ steps.semver_parser.outputs.major }}"
            echo "v${{ steps.semver_parser.outputs.minor }}"
            echo "v${{ steps.semver_parser.outputs.patch }}"
            echo "v${{ steps.semver_parser.outputs.prerelease }}"
            echo "v${{ steps.semver_parser.outputs.build }}"
            echo "v${{ steps.semver_parser.outputs.fullversion }}"
