name: Pre-Release

on:
  release:
    # See: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
    # > Note: The prereleased type will not trigger for pre-releases published from draft releases, but the published type will trigger. If you want a workflow to run when stable and pre-releases publish, subscribe to published instead of released and prereleased.
    # So, if you Draft a prerelease apparently publishing is then impossible. 
    # I believe the workaround is to re-create the pre-release against the same tag
    types: [prereleased]

jobs:
  publish_pre_release:
    runs-on: ubuntu-latest
    name: TODO
    steps:
      - name: Derive SemVer
        id: parse
        uses: NetChris/parse-semver@11-output-nuget-microsoft-versions
      - name: SemVer Gate
        id: semver_gate
        if: ${{ steps.parse.outputs.semver_version == '' }}
        run: |
          echo Pre-Releases require a SemVer tag
          exit 1
      - name: Version Gate
        id: version_gate
        if: ${{ steps.parse.outputs.pre_release_version == '' }}
        run: |
          echo This is NOT a pre-release version.  Use a GitHub release or tag as SemVer with a pre-release version.
          exit 1
      - name: What version are we releasing?
        id: echo_version
        run: |
          echo ${{ steps.parse.outputs.semver_version }}
