name: Pre-Released Release workflow

on:
  release:
    types: [prereleased]

jobs:
  pre-released-release:
    name: Pre-Released Release job
    runs-on: ubuntu-latest
    steps:
    - name: All environment variables
      run: printenv
    - 
      name: printenv GITHUB
      run: printenv | grep ^GITHUB
    - 
      name: Prelease?
      run: echo "Prerelease? ${{ github.event.release.prerelease }}"
