name: Pre-Released Release workflow

on:
  release:
    types: [prereleased]

jobs:
  pre-released-release:
    name: Pre-Released Release job
    runs-on: ubuntu-latest
    steps:
    - 
      name: GITHUB_JOB x
      run: echo ${GITHUB_JOB}
    - 
      name: printenv
      run: printenv
    - 
      name: printenv GITHUB
      run: printenv | grep ^GITHUB
