name: Created Release workflow

on:
  release:
    types: [created]

jobs:
  created-release:
    name: Created Release job
    runs-on: ubuntu-latest
    steps:
    - 
      name: GITHUB_JOB x
      run: echo ${GITHUB_JOB}
    - 
      name: printenv
      run: printenv
    - 
      name: printenv GITHUB
      run: printenv | grep ^GITHUB
