name: Published Release workflow

on:
  release:
    types: [published]

jobs:
  published-release:
    name: Published Release job
    runs-on: ubuntu-latest
    steps:
    - 
      name: GITHUB_JOB x
      run: echo ${GITHUB_JOB}
    - 
      name: printenv
      run: printenv
    - 
      name: printenv GITHUB
      run: printenv | grep ^GITHUB
