name: Release

on:
  release:
    types: [released]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    name: TODO
    steps:
      - name: Derive SemVer
        id: parse
        uses: NetChris/parse-semver@11-output-nuget-microsoft-versions
      - name: Pre-Release
        id: pre-release
        if: ${{ github.event.release.prerelease }}
        run: |
          echo This is a pre-release type
          exit 1
      - name: Release
        id: release
        run: |
          echo ${{ steps.parse.outputs.semver_version }}
      - name: YYY
        run: echo YYY
